---
- hosts: localhost
  gather_facts: False
  vars_files:
  - ./anvil.yml
  vars:
    params: {'domain': "{{ addomain }}", 'username': "{{ aduser }}", 'password': "{{ adpassword }}", 'joined': true}
  tasks:
  - name: Get AD
    uri:
      url: "https://{{ data_cluster_mgmt_ip }}:8443/mgmt/v1.2/rest/ad"
      user: "{{ hsuser }}"
      password: "{{ password }}"
      method: GET
      body: '{}'
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
    register: ad
    # Only join when not previously joined
  - name: Join AD
    when: ad.json[0].joined == false
    uri:
      url: "https://{{ data_cluster_mgmt_ip }}:8443/mgmt/v1.2/rest/ad/{{ ad.json[0].uoid.uuid }}"
      user: "{{ hsuser }}"
      password: "{{ password }}"
      method: PUT
      body: "{{ ad.json[0] | combine(params) }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
      timeout: 500
